// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VendorRiskScoring.Infrastructure.Data;

#nullable disable

namespace VendorRiskScoring.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VendorRiskScoring.Domain.Entities.RiskAssessment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<List<string>>("Reasons")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<double>("RiskScore")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VendorId");

                    b.ToTable("RiskAssessments", (string)null);
                });

            modelBuilder.Entity("VendorRiskScoring.Domain.Entities.VendorProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FinancialHealth")
                        .HasColumnType("integer");

                    b.Property<int>("MajorIncidents")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<List<string>>("SecurityCerts")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<double>("SlaUptime")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Vendors", (string)null);
                });

            modelBuilder.Entity("VendorRiskScoring.Domain.Entities.RiskAssessment", b =>
                {
                    b.HasOne("VendorRiskScoring.Domain.Entities.VendorProfile", "Vendor")
                        .WithMany("RiskAssessments")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("VendorRiskScoring.Domain.Entities.VendorProfile", b =>
                {
                    b.OwnsOne("VendorRiskScoring.Domain.Entities.VendorDocuments", "Documents", b1 =>
                        {
                            b1.Property<Guid>("VendorProfileId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("ContractValid")
                                .HasColumnType("boolean")
                                .HasColumnName("ContractValid");

                            b1.Property<bool>("PentestReportValid")
                                .HasColumnType("boolean")
                                .HasColumnName("PentestReportValid");

                            b1.Property<bool>("PrivacyPolicyValid")
                                .HasColumnType("boolean")
                                .HasColumnName("PrivacyPolicyValid");

                            b1.HasKey("VendorProfileId");

                            b1.ToTable("Vendors");

                            b1.WithOwner()
                                .HasForeignKey("VendorProfileId");
                        });

                    b.Navigation("Documents")
                        .IsRequired();
                });

            modelBuilder.Entity("VendorRiskScoring.Domain.Entities.VendorProfile", b =>
                {
                    b.Navigation("RiskAssessments");
                });
#pragma warning restore 612, 618
        }
    }
}
